# Site Settings
title: Reiff CV
url: 'https://sbreiff.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Sarah Reiff
tagline: Genomics Scientist
pic: profile1.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I have extensive experience in genetics and genomics of various unicellular eukaryotes, including both 
free-living and parasitic. My PhD work focused on apicoplast DNA replication in the apicomplexan Toxoplasma, but 
in my postdoctoral studies I have cultivated a bioinformatics skillset and been heavily involved in the genome 
project and kinome analysis for the large ciliate Stentor. I am excited about technological advances in genomics 
and am seeking a staff position in bioinformatics/genomics or genome curation.'

#sidebar links
email: sbreiff@gmail.com
phone: #+1 415 514 4323
website: #do not add http://
linkedin: sbreiff
github: sbreiff
twitter: '@sbreiff'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
