# Site Settings
title: Reiff CV
url: 'https://sbreiff.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Sarah Reiff
tagline: Genomics Data Ecosystems
pic: profile1.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Biomedical data specialist with a passion for data harmonization, seeking new opportunities in life science 
data ecosystems. I have spent the last 5 years working to build biomedical data platforms, and my 10+ 
years of research experience in molecular biology and genomics allow me to understand the needs of the scientific 
community and serve as a liaison between users, stakeholders, and developers.
"

#sidebar links
email: sbreiff@gmail.com
phone: #+1
website: #do not add http://
linkedin: sbreiff
github: sbreiff
twitter: '@sbreiff'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
