# Site Settings
title: Reiff CV
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Sarah Reiff
tagline: Genome Biologist
pic: profile1.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I have extensive experience in genetics and genomics of various protozoa, including apicomplexan parasites. 
My graduate work focused on apicoplast DNA replication in Toxoplasma, but in my postdoctoral studies I have cultivated 
a bioinformatics skill set and been heavily involved in the genome project for the free-living ciliate Stentor. I am 
excited about bioinformatics and genomics of protists and am seeking a staff position away from the wet lab.'

#sidebar links
email: sbreiff@gmail.com
phone: +1 415 514 4323
website: #do not add http://
linkedin: sbreiff
github: sbreiff
twitter: '@sbreiff'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
